name: Build

on:
  push:
    branches:
    - master
    paths:
    - build.sh
    - Dockerfile
    - VERSION
    - .github/workflows/main.yaml

env:
  DOCKER_TAG: shenxn/pytorch-pi

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Docker login
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKERIO_USERNAME }}
        password: ${{ secrets.DOCKERIO_PASSWORD }}
    - name: Set up Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        buildx-version: latest
        qemu-version: latest
    - name: Read version
      run: echo "::set-env name=RELEASE::`cat VERSION`"
    - name: Docker build
      run: |
        docker buildx build \
          --platform linux/arm/v7 \
          --build-arg ARG_VERSION=${RELEASE} \
          --tag ${DOCKER_TAG}:latest --tag ${DOCKER_TAG}:${RELEASE} \
          --push .
